version: "3.4"

services:
  postgresql:
    image: zpbird/postgresql:12.3
    environment:
      POSTGRES_PASSWORD: 790204
    volumes:
      - "/home/zp/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  nginx:
    image: zpbird/nginx:1.18.0
    ports:
      - "80:80"    





        


